sudo: required
services:
  - docker

before_install:
  - docker build -t drewbib/docker-react -f Dockerfile.dev .

script:
  # commands to actually run test suite
  # travis is going to be watching the outputs that come from these commands
  # waiting for a failure
  - docker run -e CI=true drewbib/docker-react npm run test
  # - docker run drewbib/docker-react npm run test -- --coverage
